### ISSUE TITLE
Test suite has one failure

### ISSUE THREAD

**Issue by alexdawn** [eBay/digital-signature-nodejs-sdk#1]
## Installation

on Ubuntu 22.04.1 LTS, i'm installing dependencies with:

```bash
git clone https://github.com/eBay/digital-signature-nodejs-sdk.git
cd digital-signature-nodejs-sdk

sudo apt-get install nodejs npm  # bootstrap npm

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash # install nvm
nvm use 15.8 # needs a new enough nodejs that has an ES with the .? operator
npm install
npm run start
npm run test # getting only one failure
```
## Tests

I've tweaked test to only run jest (see issue x for issue with linter)

```
alex@alex-hp-probook:~/code/digital-signature-nodejs-sdk$ npm run test

> digital-signature-nodejs-sdk@1.0.0 test
> jest

 FAIL  __tests__/index.test.ts
  test Signature SDK
    Content-Digest
      ✓ should be able to generate for SHA256 cipher (1 ms)
      ✓ should be able to generate for SHA512 cipher
    ED25519
      ✓ should be able to generate 'signature-input' header when request has payload (1 ms)
      ✓ should be able to generate 'signature-input' header when request has no payload
      ✕ should be able to generate 'Signature' header (1 ms)
      ✓ should be able to generate 'Signature' header with given JWE (1 ms)
      ✓ should be able to generate 'x-ebay-signature-key' header (10 ms)
      ✓ should be able to sign a request (2 ms)
      ✓ should be able to validate request signature (2 ms)
      ✓ should generate a valid signature (2 ms)
      ✓ should generate a valid signature for GET requests (1 ms)
      ✓ should work when keys are provided in the config (1 ms)
    RSA
      ✓ should be able to validate request signature
      ✓ should generate a valid signature (2 ms)
      ✓ should generate a valid signature for GET requests (2 ms)

  ● test Signature SDK › ED25519 › should be able to generate 'Signature' header

    error:25066067:DSO support routines:dlfcn_load:could not load the shared library

      77 |
      78 |     // If algorithm is undefined, then it is dependent upon the private key type.
    > 79 |     const signatureBuffer: any = crypto.sign(
         |                                         ^
      80 |         undefined,
      81 |         Buffer.from(baseString),
      82 |         privateKey

      at Object.generateSignature (lib/helpers/signature-helper.ts:79:41)
      at Object.<anonymous> (__tests__/index.test.ts:81:48)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 14 passed, 15 total
Snapshots:   0 total
Time:        1.653 s
Ran all test suites.
npm ERR! code 1
npm ERR! path /home/alex/code/digital-signature-nodejs-sdk
npm ERR! command failed
npm ERR! command sh -c jest

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alex/.npm/_logs/2022-11-16T12_35_38_262Z-debug.log
```

**Comment by LokeshRishi** [comment]
@alexdawn I am unable to reproduce the issue. Could you please make sure you have the required Ubuntu libraries.
This thread might be helpful: https://github.com/nodejs/node/issues/43132
